server:
  port: 8080

spring:
  application:
    name: blog-search-service

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:blog_search
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        sql: DEBUG